name: My Data Science Journey
description: For the love of data and machines that can learn
url: https://avannaldas.github.io
permalink: /:title/
gems:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed

