# Site settings
title: avannaldas.github.io
description: For the love of data and machines that can learn
twitter_username: avannaldas
github_username: avannaldas

# Build settings
markdown: kramdown
highlighter: rouge
encoding: utf-8

permalink: /:title.html

kramdown:
  parse_block_html: true
