name: My Data Science Journey
description: For the love of data and machines that can learn
url: https://avannaldas.github.io

twitter_username: avannaldas
github_username:  avannaldas

# Build settings
markdown: kramdown
encoding: utf-8

permalink: /:title/

kramdown:
    parse_block_html: true

gems:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed
